sudo: required
services:
    - docker

before_install:
    - docker build -t hmonglee/docker-react -f Dockerfiler.dev .

script:
    - docker run -e CI=true hmonglee/docker-react npm run test -- --coverage